# Generated by Django 2.1.4 on 2019-01-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='starts',
            field=models.IntegerField(default=0),
        ),
    ]
