# Generated by Django 2.1.4 on 2019-01-10 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='starts',
        ),
    ]
