# Generated by Django 2.1.4 on 2019-01-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_task_starts'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='starts',
            field=models.IntegerField(default=0),
        ),
    ]
